export const ROUTES = {
  HOME: '/(tabs)',
  SEARCH: '/(tabs)/search',
  POST: '/(tabs)/post',
  CHAT_TAB: '/(tabs)/chat',
  PROFILE: '/(tabs)/profile',

  AD_DETAIL: '/ad/[adId]',
  SELLER_PROFILE: '/seller/[sellerId]',
  CHAT_DETAIL: '/chat/[chatId]',
  CREATE_AD: '/post/create',
  EDIT_AD: '/post/edit/[adId]',
  MY_ADS: '/my-ads',
  FAVORITES: '/favorites',
  SETTINGS: '/settings',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  PHONE_VERIFY: '/auth/phone-verify',
  CATEGORY: '/category/[categoryId]',
  REVIEWS: '/reviews/[sellerId]',
  REVIEW_CREATE: '/review/create/[sellerId]',
  REPORT: '/report',
  PREMIUM: '/premium/[adId]',
  PROFILE_EDIT: '/profile/edit',
  ABOUT_APP: '/about-app',
  ABOUT_DEVELOPER: '/about-developer',
  SEARCH_RESULTS: '/search-results',
} as const;

export const HIDE_TAB_ROUTES = [
  '/ad/',
  '/seller/',
  '/chat/',
  '/post/create',
  '/post/edit/',
  '/my-ads',
  '/favorites',
  '/settings',
  '/auth/login',
  '/auth/register',
  '/auth/phone-verify',
  '/category/',
  '/reviews/',
  '/review/create/',
  '/report',
  '/premium/',
  '/profile/edit',
  '/about-app',
  '/about-developer',
  '/search-results',
];
